# Generated by Django 4.1.7 on 2023-02-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agalery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='id',
        ),
        migrations.AddField(
            model_name='obra',
            name='artista_ptr',
            field=models.OneToOneField(auto_created=True, default=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agalery.artista'),
            preserve_default=False,
        ),
    ]
