# Generated by Django 4.1.7 on 2023-02-18 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agalery', '0002_remove_obra_artista_remove_obra_id_obra_artista_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='artista_ptr',
        ),
        migrations.AddField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='agalery.artista', verbose_name='Nombre del artista'),
        ),
        migrations.AddField(
            model_name='obra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
