# Generated by Django 4.1.7 on 2023-02-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agalery', '0003_remove_obra_artista_ptr_obra_artista_obra_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='fecha',
        ),
    ]
